# Docker Compose configuration file
#
# References:
#
# * Compose Specification | Compose file reference | Reference | Docker Docs
#   https://docs.docker.com/compose/compose-file/
#
# Copyright 2024 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0
name: editorconfig-template
services:
  # Environment for testing the project
  test-environment:
    container_name: editorconfig-template-test
    hostname: editorconfig-template-test
    image: ubuntu:24.04
    volumes:
      - type: bind
        source: ./
        target: /project
    environment:
      - http_proxy
      - https_proxy
      - HTTP_PROXY
      - HTTPS_PROXY

      # Set this environment variable to your local timezone settings
      # for proper operation timestamp
      #- TZ=CST-8
    command: sleep infinity
