# REUSE licensing information association file
#
# References:
#
# * REUSE.toml | REUSE Specification – Version 3.2 | REUSE
#   https://reuse.software/spec-3.2/#reusetoml
#
# Copyright 2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0+

version = 1

[[annotations]]
path = [
    "*.README.md",
    "**/README.md"
]
SPDX-FileCopyrightText = '2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>'
SPDX-License-Identifier = 'WTFPL'

[[annotations]]
path = "continuous-integration/README*"
SPDX-FileCopyrightText = '2021 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>'
SPDX-License-Identifier = 'CC-BY-SA-4.0'
